[workspace]
resolver = "2"
members = [
  "main",
  "notification/channels/android_channel",
  "notification/channels/discord_channel",
  "notification/channels/email_channel",
  "notification/channels/ios_channel",
  "notification/channels/linux_channel",
  "notification/channels/macos_channel",
  "notification/channels/slack_channel",
  "notification/channels/sms_channel",
  "notification/channels/telegram_channel",
  "notification/channels/web_channel",
  "notification/channels/webhook_channel",
  "notification/channels/whatsapp_channel",
  "notification/channels/window_channel",
  "notification/core",
]
