[workspace]
resolver = "2"
members = [
    "main",
    "notification_core",
    "channels/sms_channel",
    "channels/email_channel",
    "channels/slack_channel", "channels/android_channel", "channels/ios_channel", "channels/macos_channel", "channels/linux_channel", "channels/window_channel", "channels/web_channel", "channels/whatsapp_channel", "channels/telegram_channel", "channels/webhook_channel",
]
